spring:
  application:
    name: movie-ticket-booking-system-api
  #DATABASE CONFIGURATION
  datasource:
    url: mysql://localhost:3306/springboot_movie_ticket_db?createDatabaseIfNotExist=true
    username: root
    password: Hanzo@25
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


